- name: My Playbook
  hosts: all
  become: true
  roles:
    - OS_Hardening
  tasks:
          # - include_tasks: /home/ashishkadian239/iitb/roles/OS_Hardening/tasks/update.yml
          # - include_tasks: /home/ashishkadian239/iitb/roles/OS_Hardening/tasks/firewall.yml
          # - include_tasks: /home/ashishkadian239/iitb/roles/OS_Hardening/tasks/kernel.yml
    - include_tasks: /home/ashishkadian239/iitb/roles/OS_Hardening/tasks/openssh.yml
