- name: Install required packages
  apt:
    name:
      - apache2
      - libapache2-mod-security2
      - libapache2-mod-evasive
    state: present

- name: Configure CAPTCHA feature
  copy:
    src: path/to/captcha.conf
    dest: /etc/apache2/conf-available/
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart Apache

- name: Configure Session Timeout
  lineinfile:
    path: /etc/php/php.ini
    regexp: '^session\.gc_maxlifetime'
    line: 'session.gc_maxlifetime = 1800'
  notify:
    - Restart Apache

- name: Configure Admin IP Access
  copy:
    src: path/to/admin_ip_access.conf
    dest: /etc/apache2/conf-available/
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart Apache

- name: Enable Apache modules
  apache2_module:
    name:
      - security2
      - evasive
    state: present
  notify:
    - Restart Apache

- name: Configure Password Hashing
  lineinfile:
    path: /etc/mysql/my.cnf
    regexp: '^default_authentication_plugin'
    line: 'default_authentication_plugin = mysql_native_password'
  notify:
    - Restart MySQL
