- name: Check if Apache configuration file exists
  stat:
    path: /etc/httpd/conf/httpd.conf
  register: conf_file

tasks:
  - name: Copy Apache configuration template
    template:
      src: templates/httpd.conf.j2  # Path to your Apache configuration template file
      dest: /etc/httpd/conf/httpd.conf  # Destination path of the Apache configuration file
      owner: root
      group: root
      mode: '0644'
    notify:
      - restart apache

  - name: Disable application directory listing
    lineinfile:
      path: /etc/httpd/conf/httpd.conf  # Replace with the path to your Apache configuration file
      regex: "^Options"
      line: "Options -Indexes"
    notify:
      - restart apache

