- name: Restrict incoming traffic to local network
  ufw:
    rule: deny
    direction: incoming
    port: http
    proto: tcp
    state: enabled

- name: Allow incoming traffic from local network
  ufw:
    rule: allow
    direction: incoming
    port: http
    proto: tcp
    state: enabled

- name: Restrict outgoing traffic to local network
  ufw:
    rule: deny
    direction: outgoing
    port: http
    proto: tcp
    state: enabled

- name: Allow outgoing traffic to local network
  ufw:
    rule: allow
    direction: outgoing
    port: http
    proto: tcp
    state: enabled

