- name: Create a non-root user
  user:
    name: myappuser
    state: present
    shell: /bin/bash
    create_home: yes

- name: Set ownership and permissions for the application directory
  file:
    path: /path/to/application
    owner: myappuser
    group: myappuser
    mode: "0755"
    recurse: yes

- name: Update the application process configuration file
  lineinfile:
    path: /path/to/application/config.conf
    line: "user=myappuser"
    state: present

- name: Restart the application process
  service:
    name: myappservice
    state: restarted

