- name: Replace "@" with "[at]"
  lineinfile:
    path: /path/to/config/file
    regex: '(.*)@(.*)\.(.*)'
    line: '\1[at]\2[dot]\3'
    backup: yes
  notify:
    - restart_service

- name: Replace "." with "[dot]"
  lineinfile:
    path: /path/to/config/file
    regex: '(.*)\.([a-zA-Z]+)'
    line: '\1[dot]\2'
    backup: yes

