- name: Set correct file permissions for dot files
  file:
    path: "/home/{{ item }}/"
    state: directory
    mode: "0755"
    recurse: yes
  with_items:
    - asc
    - wild_one
    - ashishkadian239

