- name: Update Ubuntu
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes

- name: Disable automounting for CD/DVDs and USBs
  mount:
    path: /media
    src: none
    fstype: none
    opts: "noauto"
    state: present
    dump: "0"
    passno: "0"

- name: Ensure that password is set for single user mode
  lineinfile:
    path: /etc/sysconfig/init
    regexp: '^SINGLE=/sbin/sulogin'
    line: 'SINGLE=/sbin/sulogin -p'
    state: present
    create: yes
    mode: '0644'
    backup: yes

